# call PowerShell script and return JSON
UserParameter=services.top5cpu,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\get-top5-cpu-svc.ps1"
UserParameter=services.top5ram,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\get-top5-ram-svc.ps1"