{
 "title": "NXOS VPC",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "switch_name",
    "label": "Switch Name",
    "query": {
     "query": "label_values(nxos_vpc_peer_link_health,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VPC Peer Link Health",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nxos_vpc_peer_link_health", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nxos_vpc_uptime{name='$switch_name'}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nxos_vpc_peer_link_health{name='$switch_name'}",
     "legendFormat": "Domain ID: {{domain_id}}"
    },
    {
     "expr": "nxos_vpc_peer_link_health{name='$switch_name'}",
     "legendFormat": "VRF: {{vrf}}"
    },
    {
     "expr": "nxos_vpc_peer_keepalive_health{name='$switch_name'}",
     "legendFormat": "Peer Keepalive: {{state}}"
    },
    {
     "expr": "nxos_vpc_peer_link_health{name='$switch_name'}",
     "legendFormat": "Peer Link: {{state}} - {{reason}}"
    }
   ]
  },
  {
   "title": "VPC Peer Keepalive Health",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "targets": [
    { "expr": "nxos_vpc_peer_keepalive_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "VPC Consistency Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "nxos_vpc_consistency_status{name='$switch_name'} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPC PortChannel Health",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "nxos_vpc_portchannel_health{name='$switch_name'} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NXOS VPC Exporter Target Status",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nxos_vpc_scrape_up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "NXOS VPC Exporter Target Query Duration ",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nxos_vpc_scrape_duration_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}