{
 "title": "ECS Node System",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "influxdb",
    "label": "InfluxDB",
    "query": {
     "query": "label_values(ecs_memory_total_bytes,influx_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(ecs_memory_total_bytes{influx_name=\"$influxdb\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n<h2>Disk 📁</h2>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<center>\n<h2>Memory 💾</h2>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<center>\n<h2>CPU 🔳</h2>\n</center>"
   }
  },
  {
   "title": "Inodes Usage %",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ecs_disk_inodes_used{node='$node'} / ecs_disk_inodes_total{node='$node'}) * 100",
     "legendFormat": "used %"
    },
    {
     "expr": "(ecs_disk_inodes_free{node='$node'} / ecs_disk_inodes_total{node='$node'}) * 100",
     "legendFormat": "free %"
    }
   ]
  },
  {
   "title": "inodes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_disk_inodes_used{node='$node'}",
     "legendFormat": "Used inodes"
    },
    {
     "expr": "ecs_disk_inodes_free{node='$node'}",
     "legendFormat": "Free inodes"
    },
    {
     "expr": "ecs_disk_inodes_total{node='$node'}",
     "legendFormat": "Total inodes"
    }
   ]
  },
  {
   "title": "Disk Write Latency ms",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_disk_write_latency_ms{node='$node'}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (ecs_memory_free_bytes{node='$node'} / ecs_memory_total_bytes{node='$node'} * 100)",
     "legendFormat": "used %"
    },
    {
     "expr": "ecs_memory_free_bytes{node='$node'} / ecs_memory_total_bytes{node='$node'} * 100",
     "legendFormat": "free %"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_cpu_usage_percent{node='$node'}",
     "legendFormat": "used %"
    },
    {
     "expr": "100 - ecs_cpu_usage_percent{node='$node'}",
     "legendFormat": "free %"
    }
   ]
  },
  {
   "title": "Memory Usage % Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (ecs_memory_free_bytes{node='$node'} / ecs_memory_total_bytes{node='$node'} * 100)",
     "legendFormat": "used %"
    }
   ]
  },
  {
   "title": "CPU Usage % Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecs_cpu_usage_percent{node='$node'}",
     "legendFormat": "used %"
    }
   ]
  },
  {
   "title": "Disk Usage % Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecs_disk_usage_percent{node='$node'}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk Read Latency ms",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_disk_read_latency_ms{node='$node'}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Memory Usage Bytes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_memory_total_bytes{node='$node'} - ecs_memory_free_bytes{node='$node'}",
     "legendFormat": "Used"
    },
    {
     "expr": "ecs_memory_free_bytes{node='$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "ecs_memory_total_bytes{node='$node'}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage Detailed",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_cpu_usage_system{node='$node'}",
     "legendFormat": "system apps usage %"
    },
    {
     "expr": "ecs_cpu_usage_user{node='$node'}",
     "legendFormat": "user apps usage %"
    },
    {
     "expr": "ecs_cpu_usage_iowait{node='$node'}",
     "legendFormat": "pending io usage %"
    },
    {
     "expr": "ecs_cpu_usage_percent{node='$node'} - (ecs_cpu_usage_iowait{node=\"$node\"} + ecs_cpu_usage_user + ecs_cpu_usage_system)",
     "legendFormat": "misc usage %"
    },
    {
     "expr": "100 - ecs_cpu_usage_percent{node='$node'}",
     "legendFormat": "free %"
    }
   ]
  },
  {
   "title": "Disk Space Usage Bytes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecs_disk_usage_bytes{node='$node'}",
     "legendFormat": "{{path}}: used"
    },
    {
     "expr": "ecs_disk_free_bytes{node='$node'}",
     "legendFormat": "{{path}}: free"
    },
    {
     "expr": "ecs_disk_total_bytes{node='$node'}",
     "legendFormat": "{{path}}: total"
    }
   ]
  }
 ]
}