services:
  restserver:
    image: restic/rest-server:latest
    container_name: restserver
    ports:
      - "8000:8000"
    environment:
      OPTIONS: "--prometheus --prometheus-no-auth --private-repos"
    volumes:
      - /opt/s3-mount/rest-server-data:/data
    restart: always

  sintinel:
    image: sintinel:1.1
    container_name: sintinel
    env_file:
      - .env
    depends_on:
      - restserver
    volumes:
      # clients list (read-only)
      - /opt/compose-files/sintinel/sintinel_clients.txt:/opt/scripts/sintinel_clients.txt:ro

      # mount private key at the same filename that SSH_KEY_NAME points to
      - /opt/compose-files/sintinel/id_ed25519_pgbackup:/home/sintinel/.ssh/id_ed25519_pgbackup:ro

      # persist restore/cache/logs on host
      - /opt/data/sintinel_data/restore:/opt/sintinel/restore
      - /opt/data/sintinel_data/cache:/opt/sintinel/cache
      - /opt/data/sintinel_data/logs:/var/log/sintinel
    restart: on-failure