{
 "title": "Sintinel",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Last Backup Job Status",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sintinel_backup_success", "legendFormat": "{{client}} | {{backup_dir}}" }
   ]
  },
  {
   "title": "Last Backup Job Duration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sintinel_backup_duration_seconds",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rest_server_blob_write_bytes_total) by (user)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Duration Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sintinel_backup_duration_seconds",
     "legendFormat": "{{client}}"
    }
   ]
  }
 ]
}